apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: springboot-crud-k8s
          image: nehadangat17/employeesystem:latest
          ports:
            - containerPort: 1999
          env:   
            - name: DB_HOST   
              value: mysql
            - name: DB_NAME  
              value: employeedb           
            - name: DB_USERNAME  
              value: root              
            - name: DB_PASSWORD 
              value: root              

---

apiVersion: v1 
kind: Service 
metadata: 
  name: springboot-crud-svc
spec:
  selector:
    app: springboot-k8s-mysql
  ports:
    - protocol: "TCP"
      port: 1999 
      targetPort: 1999 
  type: NodePort
